baseURL = "https://president810.github.io/Cpp-Interview-Notes/"
languageCode = "en-us"
title = "C++ Interview Notes"
author = "Zhong Kaining"
description = ""
introDescription = ""
mobileNavigation = "right"
toc = true
theme = "hugo-clarity"
publishDir = "docs"
contentdir = "content"
layoutdir = "layouts"